name: ğŸ”— AutoCorrect ç©ºæ ¼è¯­æ³•æ£€æŸ¥

on: 
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    name: AutoCorrect
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout from repository
          uses: actions/checkout@v5
        
        - name: Setup Node.js
          uses: actions/setup-node@v5
          with:
            node-version: '20'
          
        - name: Install nodejs dependencies
          run: yarn add autocorrect-node
        
        - name: Run autocorrect lint
          run: yarn autocorrect --config .autocorrectrc --lint --no-diff-bg-color **/*.md  || true 
          
        - name: Run autocorrect fix
          run: yarn autocorrect --fix **/*.md

        - name: Markdown add spaces
          uses: peter-evans/create-pull-request@v7
          with:
             commit-message: "Markdown add spaces"
             labels: "Markdown"
             delete-branch: true
             title: Markdown add spaces
             body: æ ¼å¼åŒ–â€”â€”Markdown è‡ªåŠ¨åŠ ç©ºæ ¼
