name: ğŸ”— markdownlint-cli2 è¯­æ³•æ£€æŸ¥

# Disable automatic runs
on: [workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          config: '.github/.markdownlint.json'
          fix: true
          globs: '**/*.md'

      - name: markdownlint cli2 RP
        if: failure()
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Markdown æ ¼å¼åŒ–"
          labels: "Markdown"
          delete-branch: true
          title: markdownlint
          body: |
            æ ¼å¼åŒ–â€”â€”Markdown