name: ğŸ”— md-padding è‡ªåŠ¨åŠ ç©ºæ ¼

on: 
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    name: md-padding
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout from repository
          uses: actions/checkout@v5
        
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'
          
        - name: Install Node.js dependencies 
          run: npm i -g md-padding@latest
        
        - name: Run md-padding lint
          run: find "$(pwd)" -type f -name "*.md" | xargs -I {} npx mdp -i {}

        - name: Markdown add spaces
          uses: peter-evans/create-pull-request@v7
          with:
             commit-message: "Markdown add spaces"
             labels: "Markdown"
             delete-branch: true
             title: Markdown add spaces
             body: æ ¼å¼åŒ–â€”â€”ä½¿ç”¨ md-padding ç»™ Markdown è‡ªåŠ¨åŠ ç©ºæ ¼