name: markdownlint-cli2 语法检查


on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 15 * *"


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v16
      continue-on-error: true
      with:
        config: '.github/.markdownlint.json'
        fix: true
        globs: '**/*.md'
    - name: Commit markdown-lint changes
      run: |
        git config --global user.name 'ykla'
        git config --global user.email 'yklaxds@gmail.com'
        git commit -am "自动改正 Markdown 拼写格式相关" || echo "未改变任何东西"
        git push
        rm -fr vendor